name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run deployment script
      run: |
        chmod +x ./deploy-bicep.sh
        ./deploy-bicep.sh GlobalTeamBot-RG template.bicep parameters.json
